# Generated by Django 2.2 on 2022-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0022_auto_20220421_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
