# Generated by Django 4.0.4 on 2022-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0024_project_hsc_percentage_project_ssc_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pg_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ug_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
