# Generated by Django 4.0.4 on 2022-04-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0025_project_pg_percentage_project_ug_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
