# Generated by Django 4.0.4 on 2022-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0026_project_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
