# Generated by Django 4.0.4 on 2022-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0027_project_college_name_project_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='about_us',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
