# Generated by Django 4.0.4 on 2022-04-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0029_project_college_or_university_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='college_name',
            new_name='hsc_college_name',
        ),
    ]
