# Generated by Django 4.0.4 on 2022-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0030_rename_college_name_project_hsc_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specialization',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
